export const colors = {
  light: {
    neutral: {
      colorBgBase: '#ffffff',
      colorTextBase: '#000000',
      transparent: '#000000',
      text: {
        colorText: '#1a1a1a',
        colorTextSecondary: '#404040',
        colorTextTertiary: '#666666',
        colorTextQuaternary: '#999999',
        colorTextQuinternary: '#cccccc',
        colorTextLightSolid: '#ffffff',
        colorTextHeading: '#1a1a1a',
        colorTextLabel: '#404040',
        colorTextDescription: '#404040',
        colorTextDisabled: '#999999',
        colorTextPlaceholder: '#666666',
      },
      icon: {
        colorIcon: '#404040',
        colorIconHover: '#1a1a1a',
      },
      bg: {
        colorBgPrimary: '#ffffff',
        colorBgSecondary: '#f5f5f5',
        colorBgTertiary: '#ececec',
        colorBgQuarternary: '#d9d9d9',
        colorBgInvert: '#212121',
        colorBgFooter: '#1E1E1E',
      },
      border: {
        colorBorder: '#f4f4f4',
        colorBorderSecondary: '#d9d9d9',
        colorBorderBrand: '#ffdc00',
        colorBorderPositive: '#005c00',
        colorBorderNegative: '#b00015',
        colorWhite: '#ffffff',
        colorBorderAlert: '#b74a01',
        colorBorderInfo: '#0100b2',
        colorBorderInvert: '#eaeaea',
      },
      divider: {
        colorDivider: '#bcbcbc',
        colorDividerAlt: '#191919',
        colorDividerBrand: '#ffdc00',
        colorDividerSecondary: '#293570',
        colorDividerPositive: '#005c00',
        colorDividerNegative: '#b00015',
        colorDividerAlert: '#b74a01',
        colorDividerInfo: '#0100b2',
        colorDividerInvert: '#585858',
      },
    },
    theme: {
      primary: {
        colorPrimary: '#ffdc00',
        colorPrimaryBg: '#050505',
        colorPrimaryBgHover: '#ffef8a',
        colorPrimaryBorder: '#ffdc00',
        colorPrimaryBorderHover: '#ffe333',
        colorPrimaryHover: '#ffe333',
        colorPrimaryActive: '#ffef8a',
        colorPrimaryTextHover: '#ffdc00',
        colorPrimaryText: '#8c7900',
        colorPrimaryTextActive: '#ffe333',
      },
      secondary: {
        colorSecondary: '#293570',
        colorSecondaryHover: '#374695',
        colorSecondaryActive: '#4458b9',
        colorSecondaryBg: '#dae2fd',
        colorSecondaryBgHover: '#90a5f9',
        colorSecondaryBorder: '#293570',
        colorSecondaryBorderHover: '#374695',
        colorSecondaryTextHover: '#374695',
        colorSecondaryText: '#293570',
        colorSecondaryIcon: '#8124B2',
      },
      success: {
        colorSuccess: '#45b12e',
        colorSuccessBg: '#e5ffe5',
        colorSuccessBgHover: '#c3fab8',
        colorSuccessBorder: '#45b12e',
        colorSuccessBorderHover: '#71f255',
        colorSuccessHover: '#71f255',
        colorSuccessActive: '#c3fab8',
        colorSuccessTextHover: '#45b12e',
        colorSuccessText: '#005c00',
        colorSuccessTextActive: '#c3fab8',
      },
      warning: {
        colorWarning: '#f67701',
        colorWarningBg: '#fff1e0',
        colorWarningBgHover: '#ffd8b2',
        colorWarningBorder: '#f67701',
        colorWarningBorderHover: '#ffa959',
        colorWarningHover: '#ffa959',
        colorWarningActive: '#ffd8b2',
        colorWarningTextHover: '#f67701',
        colorWarningText: '#b74a01',
        colorWarningTextActive: '#ffd8b2',
      },
      info: {
        colorInfo: '#3371c4',
        colorInfoBg: '#e6edf8',
        colorInfoBgHover: '#b0c8e8',
        colorInfoBorder: '#3371c4',
        colorInfoBorderHover: '#5488cd',
        colorInfoHover: '#5488cd',
        colorInfoActive: '#b0c8e8',
        colorInfoTextHover: '#3371c4',
        colorInfoText: '#002b64',
        colorInfoTextActive: '#b0c8e8',
      },
      error: {
        colorError: '#e2001b',
        colorErrorBg: '#ffe8e5',
        colorErrorBgHover: '#ff99a5',
        colorErrorBorder: '#e2001b',
        colorErrorBorderHover: '#ff1431',
        colorErrorHover: '#ff1431',
        colorErrorActive: '#ff99a5',
        colorErrorTextHover: '#e2001b',
        colorErrorText: '#b00015',
        colorErrorTextActive: '#ff99a5',
      },
    },
  },
  dark: {
    neutral: {
      colorBgBase: '#000000',
      colorTextBase: '#ffffff',
      transparent: '#ffffff',
      text: {
        colorText: '#ffffffd8',
        colorTextSecondary: '#ffffffa5',
        colorTextTertiary: '#ffffff72',
        colorTextQuaternary: '#ffffff3f',
        colorTextQuinternary: '#ffffff',
        ColorTextLightSolid: '#ffffff',
        colorTextHeading: '#ffffffd8',
        colorTextLabel: '#ffffffa5',
        colorTextDescription: '#ffffff72',
        colorTextDisabled: '#ffffff3f',
        colorTextPlaceholder: '#ffffff72',
      },
      icon: {
        colorIcon: '#ffffff72',
        colorIconHover: '#ffffffd8',
      },
      bg: {
        colorBgPrimary: '#141414',
        colorBgSecondary: '#1f1f1f',
        colorBgTertiary: '#000000',
        colorBgQuarternary: '#d9d9d9',
        colorBgInvert: '#ffffff',
      },
      border: {
        colorBorder: '#424242',
        colorBorderSecondary: '#303030',
        colorBorderBrand: '#ffffff14',
        colorBorderPositive: '#ffffff0a',
        colorBorderNegative: '#ffffff1e',
        colorWhite: '#ffffff',
        colorBorderAlert: '#ffffff2d',
        colorBorderInfo: '#ffffff0a',
        colorBorderInvert: '#ffffff0a',
      },
      divider: {
        colorDivider: '#ffffff2d',
        colorDividerAlt: '#ffffff1e',
        colorDividerBrand: '#ffffff14',
        colorDividerSecondary: '#ffffff',
        colorDividerPositive: '#ffffff0a',
        colorDividerNegative: '#ffffff1e',
        colorDividerAlert: '#ffffff2d',
        colorDividerInfo: '#ffffff0a',
        colorDividerInvert: '#ffffff',
      },
    },
    theme: {
      primary: {
        colorPrimary: '#1677ff',
        colorPrimaryBg: '#e6f4ff',
        colorPrimaryBgHover: '#bae0ff',
        colorPrimaryBorder: '#91caff',
        colorPrimaryBorderHover: '#69b1ff',
        colorPrimaryHover: '#0958d9',
        colorPrimaryActive: '#4096ff',
        colorPrimaryTextHover: '#0958d9',
        colorPrimaryText: '#1677ff',
        colorPrimaryTextActive: '#4096ff',
      },
      secondary: {
        colorSecondary: '#ffdc00',
        colorSecondaryHover: '#ffe333',
        colorSecondaryActive: '#ffef8a',
        colorSecondaryBg: '#ffffff',
        colorSecondaryBgHover: '#ffffff',
        colorSecondaryBorder: '#ffffff',
        colorSecondaryBorderHover: '#ffffff',
        colorSecondaryTextHover: '#ffffff',
        colorSecondaryText: '#ffffff',
        colorSecondaryTextActive: '#ffffff',
      },
      success: {
        colorSuccess: '#52c41a',
        colorSuccessBg: '#f6ffed',
        colorSuccessBgHover: '#d9f7be',
        colorSuccessBorder: '#b7eb8f',
        colorSuccessBorderHover: '#95de64',
        colorSuccessHover: '#95de64',
        colorSuccessActive: '#73d13d',
        colorSuccessTextHover: '#389e0d',
        colorSuccessText: '#52c41a',
        colorSuccessTextActive: '#73d13d',
      },
      warning: {
        colorWarning: '#faad14',
        colorWarningBg: '#fffbe6',
        colorWarningBgHover: '#fff1b8',
        colorWarningBorder: '#ffe58f',
        colorWarningBorderHover: '#ffd666',
        colorWarningHover: '#ffd666',
        colorWarningActive: '#ffc53d',
        colorWarningTextHover: '#d48806',
        colorWarningText: '#faad14',
        colorWarningTextActive: '#ffc53d',
      },
      info: {
        colorInfo: '#ffdc00',
        colorInfoBg: '#fffad9',
        colorInfoBgHover: '#ffef8a',
        colorInfoBorder: '#ffdc00',
        colorInfoBorderHover: '#ffe333',
        colorInfoHover: '#ffe333',
        colorInfoActive: '#ffef8a',
        colorInfoTextHover: '#ffdc00',
        colorInfoText: '#8c7900',
        colorInfoTextActive: '#ffe333',
      },
      error: {
        colorError: '#dc4446',
        colorErrorBg: '#2c1618',
        colorErrorBgHover: '#451d1f',
        colorErrorBorder: '#5b2526',
        colorErrorBorderHover: '#7e2e2f',
        colorErrorHover: '#e86e6b',
        colorErrorActive: '#ad393a',
        colorErrorTextHover: '#e86e6b',
        colorErrorText: '#dc4446',
        colorErrorTextActive: '#ad393a',
      },
    },
  },
};
